# Spring Data Source 설정 
spring:
  datasource:
    url: jdbc:mysql://192.168.88.128:3306/kim?userSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 0180
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        show_sql: true 
        format_sql: true 
    jakarta:
      persistence:
        jdbc:
          url: jdbc:mysql://192.168.88.128:3306/kim?userSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul

